afup_barometre_homepage:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /report/company_type
        permanent: true

afup_barometre_report_company_size:
    pattern:  /report/company_size
    defaults: { _controller: AfupBarometreBundle:ReportCompanySize:index }

afup_barometre_report_company_type:
    pattern:  /report/company_type
    defaults: { _controller: AfupBarometreBundle:ReportCompanyType:index }

afup_barometre_report_salary:
    pattern:  /report/salary
    defaults: { _controller: AfupBarometreBundle:ReportSalary:index }

afup_barometre_report_speciality:
    pattern:  /report/speciality
    defaults: { _controller: AfupBarometreBundle:ReportSpeciality:index }
